### ISSUE TITLE
Silent Startup

### ISSUE THREAD

**Issue by DXsmiley** [rscarson/Lavendeux#11]
I currently have Lavendeux set to run when I start my computer (I placed a shortcut in the startup folder inside the start menu, and it works great).

However, the program always produces a popup message reminding me that it's running, which I find annoying. An option to suppress the startup message would be great.

**Comment by rscarson** [comment]
No problem! I'll add that option tonight or tomorrow :)

**Comment by rscarson** [comment]
https://github.com/rscarson/Lavendeux/releases/tag/v0.3.1

There you go!

**Comment by DXsmiley** [comment]
Thankyou :)
